# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: actionlint
'on':
  pull_request:
    paths: &paths ['.github/workflows/**']
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: |
          sum=8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8
          tar=actionlint.tar.gz
          ver=1.7.12
          srv=https://github.com/rhysd/actionlint/releases/download
          curl \
            --fail \
            --location \
            --output "$tar" \
            --show-error \
            --silent \
            "$srv/v$ver/actionlint_${ver}_linux_amd64.tar.gz"
          echo "$sum  $tar" | sha256sum --check --quiet
          tar -xzf "$tar" actionlint
          ./actionlint
