# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: checkmake
'on':
  pull_request:
    paths: &paths
      - '**.mk'
      - '**/Makefile'
      - .github/workflows/checkmake.yml
      - Makefile
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  checkmake:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - run: |
          bin=/usr/local/bin/checkmake
          sum=e2effb876913f3ee2caef0ba35f6202c5e8a3cd55a077d8d2b9ce2034257b6af
          ver=0.3.2
          srv=https://github.com/checkmake/checkmake/releases/download
          curl \
            --fail \
            --location \
            --output "$bin" \
            --show-error \
            --silent \
            "$srv/v$ver/checkmake-v$ver.linux.amd64"
          echo "$sum  $bin" | sha256sum --check --quiet
          chmod +x "$bin"
          find . -path ./.git -prune -o \
            \( -name Makefile -o -name '*.mk' \) -print0 |
            xargs \
              --no-run-if-empty \
              --null \
              "$bin"
